// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-data-api/internal/facade (interfaces: APIFacadeI)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboard "github.com/calebtracey/rugby-models/pkg/dtos/request/leaderboard"
	leaderboard0 "github.com/calebtracey/rugby-models/pkg/dtos/response/leaderboard"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIFacadeI is a mock of APIFacadeI interface.
type MockAPIFacadeI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIFacadeIMockRecorder
}

// MockAPIFacadeIMockRecorder is the mock recorder for MockAPIFacadeI.
type MockAPIFacadeIMockRecorder struct {
	mock *MockAPIFacadeI
}

// NewMockAPIFacadeI creates a new mock instance.
func NewMockAPIFacadeI(ctrl *gomock.Controller) *MockAPIFacadeI {
	mock := &MockAPIFacadeI{ctrl: ctrl}
	mock.recorder = &MockAPIFacadeIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIFacadeI) EXPECT() *MockAPIFacadeIMockRecorder {
	return m.recorder
}

// GetAllLeaderboardData mocks base method.
func (m *MockAPIFacadeI) GetAllLeaderboardData(arg0 context.Context) leaderboard0.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllLeaderboardData", arg0)
	ret0, _ := ret[0].(leaderboard0.Response)
	return ret0
}

// GetAllLeaderboardData indicates an expected call of GetAllLeaderboardData.
func (mr *MockAPIFacadeIMockRecorder) GetAllLeaderboardData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllLeaderboardData", reflect.TypeOf((*MockAPIFacadeI)(nil).GetAllLeaderboardData), arg0)
}

// GetLeaderboardData mocks base method.
func (m *MockAPIFacadeI) GetLeaderboardData(arg0 context.Context, arg1 leaderboard.Request) leaderboard0.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaderboardData", arg0, arg1)
	ret0, _ := ret[0].(leaderboard0.Response)
	return ret0
}

// GetLeaderboardData indicates an expected call of GetLeaderboardData.
func (mr *MockAPIFacadeIMockRecorder) GetLeaderboardData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaderboardData", reflect.TypeOf((*MockAPIFacadeI)(nil).GetLeaderboardData), arg0, arg1)
}
