// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-data-api/internal/dao/comp (interfaces: DAOI)

// Package compmocks is a generated GoMock package.
package compmocks

import (
	context "context"
	reflect "reflect"

	models "github.com/calebtracey/rugby-models/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDAOI is a mock of DAOI interface.
type MockDAOI struct {
	ctrl     *gomock.Controller
	recorder *MockDAOIMockRecorder
}

// MockDAOIMockRecorder is the mock recorder for MockDAOI.
type MockDAOIMockRecorder struct {
	mock *MockDAOI
}

// NewMockDAOI creates a new mock instance.
func NewMockDAOI(ctrl *gomock.Controller) *MockDAOI {
	mock := &MockDAOI{ctrl: ctrl}
	mock.recorder = &MockDAOIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDAOI) EXPECT() *MockDAOIMockRecorder {
	return m.recorder
}

// AllLeaderboardData mocks base method.
func (m *MockDAOI) AllLeaderboardData(arg0 context.Context) (models.PSQLLeaderboardDataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllLeaderboardData", arg0)
	ret0, _ := ret[0].(models.PSQLLeaderboardDataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllLeaderboardData indicates an expected call of AllLeaderboardData.
func (mr *MockDAOIMockRecorder) AllLeaderboardData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllLeaderboardData", reflect.TypeOf((*MockDAOI)(nil).AllLeaderboardData), arg0)
}

// LeaderboardData mocks base method.
func (m *MockDAOI) LeaderboardData(arg0 context.Context, arg1 string) (models.PSQLLeaderboardDataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaderboardData", arg0, arg1)
	ret0, _ := ret[0].(models.PSQLLeaderboardDataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaderboardData indicates an expected call of LeaderboardData.
func (mr *MockDAOIMockRecorder) LeaderboardData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaderboardData", reflect.TypeOf((*MockDAOI)(nil).LeaderboardData), arg0, arg1)
}
