// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-data-api/internal/dao/comp (interfaces: MapperI)

// Package compmocks is a generated GoMock package.
package compmocks

import (
	sql "database/sql"
	reflect "reflect"

	models "github.com/calebtracey/rugby-models/models"
	response "github.com/calebtracey/rugby-models/response"
	gomock "github.com/golang/mock/gomock"
)

// MockMapperI is a mock of MapperI interface.
type MockMapperI struct {
	ctrl     *gomock.Controller
	recorder *MockMapperIMockRecorder
}

// MockMapperIMockRecorder is the mock recorder for MockMapperI.
type MockMapperIMockRecorder struct {
	mock *MockMapperI
}

// NewMockMapperI creates a new mock instance.
func NewMockMapperI(ctrl *gomock.Controller) *MockMapperI {
	mock := &MockMapperI{ctrl: ctrl}
	mock.recorder = &MockMapperIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapperI) EXPECT() *MockMapperIMockRecorder {
	return m.recorder
}

// CreatePSQLCompetitionQuery mocks base method.
func (m *MockMapperI) CreatePSQLCompetitionQuery(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePSQLCompetitionQuery", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreatePSQLCompetitionQuery indicates an expected call of CreatePSQLCompetitionQuery.
func (mr *MockMapperIMockRecorder) CreatePSQLCompetitionQuery(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePSQLCompetitionQuery", reflect.TypeOf((*MockMapperI)(nil).CreatePSQLCompetitionQuery), arg0)
}

// MapPSQLLeaderboardDataToResponse mocks base method.
func (m *MockMapperI) MapPSQLLeaderboardDataToResponse(arg0, arg1 string, arg2 models.PSQLLeaderboardDataList) response.LeaderboardResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapPSQLLeaderboardDataToResponse", arg0, arg1, arg2)
	ret0, _ := ret[0].(response.LeaderboardResponse)
	return ret0
}

// MapPSQLLeaderboardDataToResponse indicates an expected call of MapPSQLLeaderboardDataToResponse.
func (mr *MockMapperIMockRecorder) MapPSQLLeaderboardDataToResponse(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapPSQLLeaderboardDataToResponse", reflect.TypeOf((*MockMapperI)(nil).MapPSQLLeaderboardDataToResponse), arg0, arg1, arg2)
}

// MapPSQLRowsToLeaderboardData mocks base method.
func (m *MockMapperI) MapPSQLRowsToLeaderboardData(arg0 *sql.Rows) models.PSQLLeaderboardDataList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapPSQLRowsToLeaderboardData", arg0)
	ret0, _ := ret[0].(models.PSQLLeaderboardDataList)
	return ret0
}

// MapPSQLRowsToLeaderboardData indicates an expected call of MapPSQLRowsToLeaderboardData.
func (mr *MockMapperIMockRecorder) MapPSQLRowsToLeaderboardData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapPSQLRowsToLeaderboardData", reflect.TypeOf((*MockMapperI)(nil).MapPSQLRowsToLeaderboardData), arg0)
}
