// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.0 DO NOT EDIT.
package openapi3

// ErrorLog defines model for ErrorLog.
type ErrorLog struct {
	Query     *string `json:"query"`
	RootCause *string `json:"rootCause"`
	Scope     *string `json:"scope"`
	Status    *string `json:"status"`
	Trace     *string `json:"trace"`
}

// ErrorLogs defines model for ErrorLogs.
type ErrorLogs = []ErrorLog

// Message defines model for Message.
type Message struct {
	Count     *string    `json:"count"`
	ErrorLog  *ErrorLogs `json:"errorLog,omitempty"`
	HostName  *string    `json:"hostName"`
	Status    *string    `json:"status"`
	TimeTaken *string    `json:"timeTaken"`
}

// TeamData defines model for TeamData.
type TeamData struct {
	Id   *string `json:"id"`
	Name *string `json:"name"`
}

// TeamDataList defines model for TeamDataList.
type TeamDataList = []TeamData

// CompetitionResponse defines model for CompetitionResponse.
type CompetitionResponse struct {
	Id      *string       `json:"id"`
	Message *Message      `json:"message,omitempty"`
	Name    *string       `json:"name,omitempty"`
	Teams   *TeamDataList `json:"teams,omitempty"`
}

// CompetitionRequest defines model for CompetitionRequest.
type CompetitionRequest struct {
	CompetitionID   *string `json:"competitionID,omitempty"`
	CompetitionName *string `json:"competitionName,omitempty"`
	Id              *string `json:"id,omitempty"`
	Source          *string `json:"source,omitempty"`
	Table           *string `json:"table,omitempty"`
}

// GetCompetitionJSONBody defines parameters for GetLeaderboardData.
type GetCompetitionJSONBody struct {
	CompetitionID   *string `json:"competitionID,omitempty"`
	CompetitionName *string `json:"competitionName,omitempty"`
	Id              *string `json:"id,omitempty"`
	Source          *string `json:"source,omitempty"`
	Table           *string `json:"table,omitempty"`
}

// GetCompetitionJSONRequestBody defines body for GetLeaderboardData for application/json ContentType.
type GetCompetitionJSONRequestBody GetCompetitionJSONBody
