// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.0 DO NOT EDIT.
package openapi3

// ErrorLog defines model for ErrorLog.
type ErrorLog struct {
	Query     *string `json:"query"`
	RootCause *string `json:"rootCause"`
	Scope     *string `json:"scope"`
	Status    *string `json:"status"`
	Trace     *string `json:"trace"`
}

// ErrorLogs defines model for ErrorLogs.
type ErrorLogs = []ErrorLog

// Message defines model for Message.
type Message struct {
	Count     *string    `json:"count"`
	ErrorLog  *ErrorLogs `json:"errorLog,omitempty"`
	HostName  *string    `json:"hostName"`
	Status    *string    `json:"status"`
	TimeTaken *string    `json:"timeTaken"`
}

// TeamLeaderboardData defines model for TeamLeaderboardData.
type TeamLeaderboardData struct {
	BonusPoints       *string `json:"bonusPoints"`
	BonusPointsLosing *string `json:"bonusPointsLosing"`
	BonusPointsTry    *string `json:"bonusPointsTry"`
	Bye               *string `json:"bye"`
	DrawCount         *string `json:"drawCount"`
	GamesPlayed       *string `json:"gamesPlayed"`
	Id                *string `json:"id"`
	LossCount         *string `json:"lossCount"`
	Name              *string `json:"name"`
	Points            *string `json:"points"`
	PointsAgainst     *string `json:"pointsAgainst"`
	PointsDiff        *string `json:"pointsDiff"`
	PointsFor         *string `json:"pointsFor"`
	TriesAgainst      *string `json:"triesAgainst"`
	TriesFor          *string `json:"triesFor"`
	WinCount          *string `json:"winCount"`
}

// TeamLeaderboardDataList defines model for TeamLeaderboardDataList.
type TeamLeaderboardDataList = []TeamLeaderboardData

// LeaderboardResponse defines model for LeaderboardResponse.
type LeaderboardResponse struct {
	Id      *string                  `json:"id"`
	Message *Message                 `json:"message,omitempty"`
	Name    *string                  `json:"name,omitempty"`
	Teams   *TeamLeaderboardDataList `json:"teams,omitempty"`
}

// LeaderboardRequest defines model for LeaderboardRequest.
type LeaderboardRequest struct {
	CompId   *string `json:"compId,omitempty"`
	CompName *string `json:"compName,omitempty"`
	Date     *string `json:"date,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// GetLeaderboardDataJSONBody defines parameters for LeaderboardData.
type GetLeaderboardDataJSONBody struct {
	CompId   *string `json:"compId,omitempty"`
	CompName *string `json:"compName,omitempty"`
	Date     *string `json:"date,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// GetLeaderboardDataJSONRequestBody defines body for LeaderboardData for application/json ContentType.
type GetLeaderboardDataJSONRequestBody GetLeaderboardDataJSONBody
