// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-data-api/internal/facade (interfaces: APIFacadeI)

// Package facade is a generated GoMock package.
package facade

import (
	context "context"
	reflect "reflect"

	request "github.com/calebtracey/rugby-data-api/external/models/request"
	response "github.com/calebtracey/rugby-data-api/external/models/response"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIFacadeI is a mock of APIFacadeI interface.
type MockAPIFacadeI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIFacadeIMockRecorder
}

// MockAPIFacadeIMockRecorder is the mock recorder for MockAPIFacadeI.
type MockAPIFacadeIMockRecorder struct {
	mock *MockAPIFacadeI
}

// NewMockAPIFacadeI creates a new mock instance.
func NewMockAPIFacadeI(ctrl *gomock.Controller) *MockAPIFacadeI {
	mock := &MockAPIFacadeI{ctrl: ctrl}
	mock.recorder = &MockAPIFacadeIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIFacadeI) EXPECT() *MockAPIFacadeIMockRecorder {
	return m.recorder
}

// SixNationsResults mocks base method.
func (m *MockAPIFacadeI) SixNationsResults(arg0 context.Context, arg1 request.CompetitionRequest) response.CompetitionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SixNationsResults", arg0, arg1)
	ret0, _ := ret[0].(response.CompetitionResponse)
	return ret0
}

// SixNationsResults indicates an expected call of SixNationsResults.
func (mr *MockAPIFacadeIMockRecorder) SixNationsResults(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SixNationsResults", reflect.TypeOf((*MockAPIFacadeI)(nil).SixNationsResults), arg0, arg1)
}
