// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-data-api/internal/facade/sixnations (interfaces: FacadeI)

// Package sixnations is a generated GoMock package.
package sixnations

import (
	context "context"
	reflect "reflect"

	request "github.com/calebtracey/rugby-data-api/external/models/request"
	response "github.com/calebtracey/rugby-data-api/external/models/response"
	gomock "github.com/golang/mock/gomock"
)

// MockFacadeI is a mock of FacadeI interface.
type MockFacadeI struct {
	ctrl     *gomock.Controller
	recorder *MockFacadeIMockRecorder
}

// MockFacadeIMockRecorder is the mock recorder for MockFacadeI.
type MockFacadeIMockRecorder struct {
	mock *MockFacadeI
}

// NewMockFacadeI creates a new mock instance.
func NewMockFacadeI(ctrl *gomock.Controller) *MockFacadeI {
	mock := &MockFacadeI{ctrl: ctrl}
	mock.recorder = &MockFacadeIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacadeI) EXPECT() *MockFacadeIMockRecorder {
	return m.recorder
}

// SixNationsCrawl mocks base method.
func (m *MockFacadeI) SixNationsCrawl(arg0 context.Context, arg1 request.CompetitionCrawlRequest) response.CompetitionCrawlResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SixNationsCrawl", arg0, arg1)
	ret0, _ := ret[0].(response.CompetitionCrawlResponse)
	return ret0
}

// SixNationsCrawl indicates an expected call of SixNationsCrawl.
func (mr *MockFacadeIMockRecorder) SixNationsCrawl(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SixNationsCrawl", reflect.TypeOf((*MockFacadeI)(nil).SixNationsCrawl), arg0, arg1)
}

// SixNationsTeams mocks base method.
func (m *MockFacadeI) SixNationsTeams(arg0 context.Context) response.CompetitionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SixNationsTeams", arg0)
	ret0, _ := ret[0].(response.CompetitionResponse)
	return ret0
}

// SixNationsTeams indicates an expected call of SixNationsTeams.
func (mr *MockFacadeIMockRecorder) SixNationsTeams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SixNationsTeams", reflect.TypeOf((*MockFacadeI)(nil).SixNationsTeams), arg0)
}
