components:
  requestBodies:
    LeaderboardRequest:
      content:
        application/json:
          schema:
            properties:
              compId:
                minLength: 1
                type: string
              compName:
                minLength: 1
                type: string
              date:
                minLength: 1
                type: string
              source:
                minLength: 1
                type: string
      description: Request used for fetching leaderboard data
      required: true
  responses:
    LeaderboardResponse:
      content:
        application/json:
          schema:
            nullable: true
            properties:
              id:
                nullable: true
                type: string
              message:
                $ref: '#/components/schemas/Message'
              name:
                type: string
              teams:
                $ref: '#/components/schemas/TeamLeaderboardDataList'
      description: Response with competition data
  schemas:
    ErrorLog:
      properties:
        query:
          nullable: true
          type: string
        rootCause:
          nullable: true
          type: string
        scope:
          nullable: true
          type: string
        status:
          nullable: true
          type: string
        trace:
          nullable: true
          type: string
      type: object
    ErrorLogs:
      items:
        $ref: '#/components/schemas/ErrorLog'
      type: array
    Message:
      properties:
        count:
          nullable: true
          type: string
        errorLog:
          $ref: '#/components/schemas/ErrorLogs'
        hostName:
          nullable: true
          type: string
        status:
          nullable: true
          type: string
        timeTaken:
          nullable: true
          type: string
      type: object
    PSQLLeaderboardData:
      properties:
        bonus_points:
          nullable: true
          type: string
        bonus_points_losing:
          nullable: true
          type: string
        bonus_points_try:
          nullable: true
          type: string
        bye:
          nullable: true
          type: string
        comp_id:
          nullable: true
          type: string
        comp_name:
          nullable: true
          type: string
        draw_count:
          nullable: true
          type: string
        games_played:
          nullable: true
          type: string
        loss_count:
          nullable: true
          type: string
        points:
          nullable: true
          type: string
        points_against:
          nullable: true
          type: string
        points_diff:
          nullable: true
          type: string
        points_for:
          nullable: true
          type: string
        team_id:
          nullable: true
          type: string
        team_name:
          nullable: true
          type: string
        tries_against:
          nullable: true
          type: string
        tries_for:
          nullable: true
          type: string
        win_count:
          nullable: true
          type: string
      type: object
    PSQLLeaderboardDataList:
      items:
        $ref: '#/components/schemas/PSQLLeaderboardData'
      type: array
    TeamLeaderboardData:
      properties:
        bonusPoints:
          nullable: true
          type: string
        bonusPointsLosing:
          nullable: true
          type: string
        bonusPointsTry:
          nullable: true
          type: string
        bye:
          nullable: true
          type: string
        drawCount:
          nullable: true
          type: string
        gamesPlayed:
          nullable: true
          type: string
        id:
          nullable: true
          type: string
        lossCount:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        points:
          nullable: true
          type: string
        pointsAgainst:
          nullable: true
          type: string
        pointsDiff:
          nullable: true
          type: string
        pointsFor:
          nullable: true
          type: string
        triesAgainst:
          nullable: true
          type: string
        triesFor:
          nullable: true
          type: string
        winCount:
          nullable: true
          type: string
      type: object
    TeamLeaderboardDataList:
      items:
        $ref: '#/components/schemas/TeamLeaderboardData'
      type: array
info:
  contact:
    url: https://github.com/CalebTracey/rugby-data-api
  description: REST API used for fetching and accessing rugby stats
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Rugby Data REST API
  version: 0.0.0
openapi: 3.0.0
paths:
  /leaderboard:
    description: Leaderboard Data
    post:
      operationId: GetLeaderboardData
      requestBody:
        $ref: '#/components/requestBodies/LeaderboardRequest'
      responses:
        "201":
          $ref: '#/components/responses/LeaderboardResponse'
        "400":
          $ref: '#/components/responses/LeaderboardResponse'
        "500":
          $ref: '#/components/responses/LeaderboardResponse'
servers:
- description: Local development
  url: http://0.0.0.0:6080
