Env: "local"
Port: "6080"
AppName: "rugby-data-api"
ClientConfig:
  Timeout: 15
  IdleConnTimeout: 30
  MaxIdleConsPerHost: 1
  MaxConsPerHost: 1
DatabaseConfigs:
  - Name: "PSQL"
    Database: "rugby_db"
    Server: "localhost:5432"
    Username: "postgres"
    Password: "password"
    Scheme: "postgres"