Env: "local"
Port: "6080"
AppName: "rugby-data-api"
ClientConfig:
  Timeout: 15
  IdleConnTimeout: 30
  MaxIdleConsPerHost: 1
  MaxConsPerHost: 1
DatabaseConfigs:
  - Name: "PSQL"
    Database: "rugby_db"
    Server: "localhost:5432"
    Username: "calebtracey"
    Password: "password"
    Scheme: "postgres"
CrawlerConfigs:
  - Name: "COLLY"
    AppsJSONPath: ""
    TimeoutSeconds: "3"
    LoadingTimeoutSeconds: "3"
    JSON: "true"
    MaxDepth: "0"
    visitedLinks: "0"
    MaxVisitedLinks: "100"
    MsDelayBetweenRequests: "10"