on: [pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Run coverage
        run: go test -coverprofile="coverage.txt" -covermode=atomic -race .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3